CREATE TABLE Readers
(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
PersonalId INTEGER NOT NULL, 
libraryCardNumber INTEGER NOT NULL,
TotalBooks INTEGER DEFAULT 0,
FOREIGN KEY (PersonalId) REFERENCES Persons (Id) ON DELETE CASCADE
)