CREATE TABLE Accounts
(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
LoginId INTEGER NOT NULL, 
Login TEXT NOT NULL, 
Password TEXT NOT NULL,
Salt NUMERIC,
FOREIGN KEY (LoginId) REFERENCES Persons (Id) ON DELETE CASCADE

